- name: fact variable
  hosts: webserver
  become: true
  tasks:
  - name: install tomcat package
    yum: name=tomcat state=present
    when: ansible_os_family == "RedHat"
  - name: install apache2 package
    package: name=apache2 state=present
    when: ansible_os_family == "Debian"
    ignore_errors: true

